/* AUTO-GENERATED by build/make_engine.mjs from build/template.html — do not edit.
   Sharpe momentum + HRP + constraint numerics, cross-checked against the NumPy
   reference (build/reference_numerics.py) via build/validate_js.mjs. */
const TD = 252;
function simpleReturns(closes){
  const r = new Array(closes.length - 1);
  for (let i = 1; i < closes.length; i++) r[i-1] = closes[i]/closes[i-1] - 1;
  return r;
}

function mean(a){ let s=0; for (const x of a) s+=x; return s/a.length; }

function sampleStd(a){
  if (a.length < 2) return 0;
  const m = mean(a); let s=0;
  for (const x of a) s += (x-m)*(x-m);
  return Math.sqrt(s/(a.length-1));
}

function sharpeMomentum(closes, asof, start, end){
  const lo = asof - start, hi = asof - end;
  if (lo < 0 || hi >= closes.length || hi - lo < 2) return null;
  const seg = closes.slice(lo, hi + 1);
  const r = simpleReturns(seg);
  if (r.length < 2) return null;
  const m = mean(r), sd = sampleStd(r);
  const annRet = m * TD, annVol = sd * Math.sqrt(TD);
  const sharpe = annVol > 0 ? annRet / annVol : 0;
  const cum = seg[seg.length-1]/seg[0] - 1;
  return { sharpe, annRet, annVol, cum, n: r.length };
}

function momentumDaily(closes, asof, startOff, endOff){
  const lo = asof - startOff, hi = asof - endOff;
  if (lo < 0 || hi >= closes.length || hi <= lo) return null;
  const seg = closes.slice(lo, hi + 1);
  for (let i = 0; i < seg.length; i++) if (seg[i] == null || !(seg[i] > 0)) return null;
  return { r: simpleReturns(seg), lo, hi, cum: seg[seg.length - 1] / seg[0] - 1 };
}

function annualizeStats(r){
  if (!r || r.length < 2) return null;
  return { annRet: mean(r) * TD, annVol: sampleStd(r) * Math.sqrt(TD) };
}

function olsFit(y, x){
  const n = Math.min(y.length, x.length);
  if (n < 60) return null;
  let my = 0, mx = 0;
  for (let i = 0; i < n; i++){ my += y[i]; mx += x[i]; }
  my /= n; mx /= n;
  let cov = 0, vx = 0;
  for (let i = 0; i < n; i++){ const dx = x[i] - mx; cov += (y[i] - my) * dx; vx += dx * dx; }
  const beta = vx > 0 ? cov / vx : 0;
  return { alpha: my - beta * mx, beta, n };
}

function momentumScore(closes, market, asof, cfg){
  const rw = momentumDaily(closes, asof, cfg.retStart, cfg.retEnd);
  if (!rw) return null;
  const vStart = cfg.matchVol ? cfg.retStart : cfg.volStart;
  const vEnd = cfg.matchVol ? cfg.retEnd : cfg.volEnd;
  const vw = momentumDaily(closes, asof, vStart, vEnd);
  if (cfg.mode !== 'return' && !vw) return null;
  let rRet = rw.r, vRet = vw ? vw.r : null, beta = null, alpha = null, cum = rw.cum;
  if (cfg.removeMkt) {
    const bw = cfg.betaWindow || 756;
    const bLo = asof - bw, bHi = asof;
    if (bLo < 0) return null;                       // insufficient history for beta
    const bseg = closes.slice(bLo, bHi + 1);
    for (let i = 0; i < bseg.length; i++) if (bseg[i] == null || !(bseg[i] > 0)) return null;
    const fit = olsFit(simpleReturns(bseg), market.slice(bLo, bHi));
    if (!fit) return null;
    alpha = fit.alpha; beta = fit.beta;
    rRet = rw.r.map((v, i) => v - alpha - beta * market[rw.lo + i]);
    if (vw) vRet = vw.r.map((v, i) => v - alpha - beta * market[vw.lo + i]);
    let cr = 1; for (const e of rRet) cr *= (1 + e); cum = cr - 1;  // cumulative residual
  }
  const ra = annualizeStats(rRet);
  if (!ra) return null;
  const va = vw ? annualizeStats(vRet) : null;
  const annRet = ra.annRet, annVol = va ? va.annVol : null;
  let score;
  if (cfg.mode === 'return') score = annRet;
  else if (cfg.mode === 'vol') score = annVol;
  else score = (annVol && annVol > 0) ? annRet / annVol : 0;
  return { annRet, annVol, score, cum, beta, alpha };
}

function covMatrix(R){                       // R: T×N returns -> N×N sample cov
  const T = R.length, Nn = R[0].length;
  const mu = new Array(Nn).fill(0);
  for (let t=0;t<T;t++) for (let j=0;j<Nn;j++) mu[j]+=R[t][j];
  for (let j=0;j<Nn;j++) mu[j]/=T;
  const cov = Array.from({length:Nn},()=>new Array(Nn).fill(0));
  for (let i=0;i<Nn;i++) for (let j=i;j<Nn;j++){
    let s=0; for (let t=0;t<T;t++) s+=(R[t][i]-mu[i])*(R[t][j]-mu[j]);
    const v = s/(T-1); cov[i][j]=v; cov[j][i]=v;
  }
  return cov;
}

function corrFromCov(cov){
  const Nn = cov.length, std = cov.map((_,i)=>Math.sqrt(cov[i][i]>0?cov[i][i]:0));
  const c = Array.from({length:Nn},()=>new Array(Nn).fill(0));
  for (let i=0;i<Nn;i++) for (let j=0;j<Nn;j++){
    if (std[i]>0 && std[j]>0){
      let v = cov[i][j]/(std[i]*std[j]);
      v = Math.max(-1, Math.min(1, v));       // stabilize
      c[i][j] = v;
    } else c[i][j] = (i===j)?1:0;
  }
  for (let i=0;i<Nn;i++) c[i][i]=1;
  return c;
}

function quasiDiagOrder(dist){
  const n = dist.length;
  if (n === 1) return [0];
  const members = {}; for (let i=0;i<n;i++) members[i]=[i];
  const D = {}; const key=(a,b)=>a<b?a+'_'+b:b+'_'+a;
  for (let i=0;i<n;i++) for (let j=i+1;j<n;j++) D[key(i,j)]=dist[i][j];
  const size={}; for (let i=0;i<n;i++) size[i]=1;
  let active = new Set(); for (let i=0;i<n;i++) active.add(i);
  let next = n; const merges = [];
  while (active.size > 1){
    let best=Infinity, ba=-1, bb=-1;
    const arr=[...active];
    for (let x=0;x<arr.length;x++) for (let y=x+1;y<arr.length;y++){
      const d = D[key(arr[x],arr[y])];
      if (d < best){ best=d; ba=arr[x]; bb=arr[y]; }
    }
    const na=size[ba], nb=size[bb];
    merges[next] = [ba, bb];
    members[next] = members[ba].concat(members[bb]);
    size[next] = na+nb;
    for (const k of active){
      if (k===ba||k===bb) continue;
      const da=D[key(ba,k)], db=D[key(bb,k)];
      D[key(next,k)] = (na*da + nb*db)/(na+nb);   // UPGMA average linkage
    }
    active.delete(ba); active.delete(bb); active.add(next); next++;
  }
  const root = next-1;
  const order=[]; const stack=[root];
  // expand root preserving left/right order
  (function expand(node){
    if (node < n){ order.push(node); return; }
    expand(merges[node][0]); expand(merges[node][1]);
  })(root);
  return order;
}

function clusterVar(cov, idx){
  let inv=[], s=0;
  for (const i of idx){ const v=1/cov[i][i]; inv.push(v); s+=v; }
  inv = inv.map(v=>v/s);
  let vv=0;
  for (let a=0;a<idx.length;a++) for (let b=0;b<idx.length;b++)
    vv += inv[a]*cov[idx[a]][idx[b]]*inv[b];
  return vv;
}

function recursiveBisection(cov, order){
  const n = cov.length; const w = new Array(n).fill(1);
  let clusters = [order.slice()];
  while (clusters.length){
    const next=[];
    for (const cl of clusters){
      if (cl.length <= 1) continue;
      const half = Math.floor(cl.length/2);
      const left = cl.slice(0,half), right = cl.slice(half);
      const vL = clusterVar(cov,left), vR = clusterVar(cov,right);
      const alpha = 1 - vL/(vL+vR);
      for (const i of left) w[i]*=alpha;
      for (const i of right) w[i]*=(1-alpha);
      next.push(left, right);
    }
    clusters = next;
  }
  const s = w.reduce((a,b)=>a+b,0);
  return w.map(x=>x/s);
}

function hrpWeights(R){
  const cov = covMatrix(R);
  const corr = corrFromCov(cov);
  const nn = cov.length;
  const dist = Array.from({length:nn},()=>new Array(nn).fill(0));
  for (let i=0;i<nn;i++) for (let j=0;j<nn;j++)
    dist[i][j] = Math.sqrt(Math.max(0,(1-corr[i][j])/2));
  const order = quasiDiagOrder(dist);
  return recursiveBisection(cov, order);
}

function applyCaps(weights, sectors, maxStock, maxSector){
  const tol=1e-9, n=weights.length;
  let w = weights.slice(); let sum=w.reduce((a,b)=>a+b,0); w=w.map(x=>x/sum);
  const secs=[...new Set(sectors)];
  if (maxStock>0 && maxStock*n < 1-tol)
    return {w, feasible:false, msg:`Infeasible: ${n} names capped at ${pct(maxStock)} hold at most ${pct(maxStock*n)}. Raise the stock cap to ≥ ${pct(1/n,1)} or add names.`};
  if (maxSector>0){
    // joint capacity: each sector can hold at most min(sectorCap, itsNames*stockCap).
    // If the sectors together can't reach 100%, the two caps are jointly infeasible
    // (a per-cap check alone misses this — e.g. 0.15 stock + 0.30 sector on a
    // concentrated basket tops out below 1).
    let capacity=0;
    for (const s of secs){
      let cnt=0; for (const x of sectors) if (x===s) cnt++;
      capacity += maxStock>0 ? Math.min(maxSector, cnt*maxStock) : maxSector;
    }
    if (capacity < 1-tol)
      return {w, feasible:false, msg: maxStock>0
        ? `Infeasible: a ${pct(maxStock)} stock cap with a ${pct(maxSector)} sector cap lets these ${secs.length} sector${secs.length>1?'s':''} hold at most ${pct(capacity)}. Loosen a cap, add names, or spread across more sectors.`
        : `Infeasible: ${secs.length} sector${secs.length>1?'s':''} capped at ${pct(maxSector)} hold at most ${pct(capacity)}. Raise the sector cap or diversify sectors.`};
  }
  for (let iter=0; iter<1000; iter++){
    let changed=false;
    if (maxStock>0){
      const over = w.map(x=>x>maxStock+tol);
      if (over.some(Boolean)){
        let excess=0; for (let i=0;i<n;i++) if (over[i]){ excess+=w[i]-maxStock; w[i]=maxStock; }
        const free=[]; let fs=0;
        for (let i=0;i<n;i++) if (!over[i] && w[i]<maxStock-tol){ free.push(i); fs+=w[i]; }
        if (!free.length) return {w, feasible:false, msg:'Infeasible: stock cap leaves no capacity to redistribute.'};
        for (const i of free) w[i]+=excess*(w[i]/fs);
        changed=true;
      }
    }
    if (maxSector>0){
      for (const s of secs){
        const mask = sectors.map(x=>x===s);
        let tot=0; for (let i=0;i<n;i++) if (mask[i]) tot+=w[i];
        if (tot>maxSector+tol){
          const excess=tot-maxSector, scale=maxSector/tot;
          for (let i=0;i<n;i++) if (mask[i]) w[i]*=scale;
          const free=[]; let fs=0;
          for (let i=0;i<n;i++){
            if (mask[i]) continue;
            if (maxStock>0 && w[i]>=maxStock-tol) continue;
            free.push(i); fs+=w[i];
          }
          if (!free.length) return {w, feasible:false, msg:'Infeasible: sector cap cannot be redistributed within the other caps. Loosen a cap or add names in other sectors.'};
          for (const i of free) w[i]+=excess*(w[i]/fs);
          changed=true;
        }
      }
    }
    if (!changed) break;
  }
  const s2=w.reduce((a,b)=>a+b,0); w=w.map(x=>x/s2);
  return {w, feasible:true, msg:'ok'};
}

function periodReturn(closes, asof, days){
  const lo=asof-days; if (lo<0) return null;
  return closes[asof]/closes[lo]-1;
}

function pct(x, dp=0){ return (x*100).toFixed(dp)+'%'; }

function signPct(x, dp=1){ return (x>=0?'+':'')+(x*100).toFixed(dp)+'%'; }

function fmtSharpe(x){ return (x>=0?'+':'')+x.toFixed(2); }

function fmtCap(x){ if(x>=1e12) return '$'+(x/1e12).toFixed(2)+'T'; if(x>=1e9) return '$'+(x/1e9).toFixed(1)+'B'; if(x>=1e6) return '$'+(x/1e6).toFixed(0)+'M'; return '$'+x; }

function clsOf(x){ return x>=0?'gain':'loss'; }

export { simpleReturns, mean, sampleStd, sharpeMomentum, momentumDaily, annualizeStats, olsFit, momentumScore, covMatrix, corrFromCov, quasiDiagOrder, clusterVar, recursiveBisection, hrpWeights, applyCaps, periodReturn, pct, signPct, fmtSharpe, fmtCap, clsOf, TD };
